package tools.lexer;

import java.io.BufferedWriter;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;

import tools.CompilerToolException;
import tools.FileGeneratorTool;

public class TokenKindGenerator extends FileGeneratorTool {

    public TokenKindGenerator(Path tokenFilePath) throws CompilerToolException {
        super(tokenFilePath);
    }

    @Override
    public void generate() throws CompilerToolException {
        // TODO Fix formatting
        try (BufferedWriter writer = new BufferedWriter(new FileWriter("src/lexer/daos/TokenKind.java"))) {
            writer.write(this.formatLine("package lexer.daos;", 0, 2));

            writer.write(this.formatLine(getAutoGeneratedWarning(), 0, 0));
            writer.write(this.formatLine("public enum TokenKind {", 0, 1));
            writer.write(this.formatLine("BogusToken, EOF,", 1, 1));

            int count = 1;
            while (this.hasNext()) {
                String line = this.next();
                String[] parts = line.split("\s+");

                if (count++ % 5 == 0) {
                    writer.write(this.formatLine("\n", 1));
                }

                writer.write(parts[0] + ", ");
            }

            writer.write(this.formatLine("\n}", 0, 1));
        } catch (IOException error) {
            // TODO come up with a meaningful message here
            throw new CompilerToolException("");
        }
    }

}
