package tools.lexer;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.nio.file.Path;
import java.util.List;

import tools.FileGeneratorTool;

public class TokenKindGenerator extends FileGeneratorTool {

    public TokenKindGenerator() throws IOException {
        super();
    }

    @Override
    protected void generate() throws IOException {
        File file = Path.of("src", "lexer", "daos", "TokenKind.java").toFile();
        System.out.println(String.format("Generating file %s", file.getName()));

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(file))) {
            writer.write(String.join("", List.of(
                    this.formatString(0, 2, "package lexer.daos;"),
                    this.autoGeneratedWarning(),
                    this.formatString(0, 1, "public enum TokenKind {"),
                    this.formatString(1, 1, "// Special TokenKinds for internal use"),
                    this.formatString(1, 2, "BogusToken, EOF,"),
                    this.formatString(1, 0, "// Generated TokenKinds (from tokens.txt)"))));

            int index = 0;
            while (this.hasNext()) {
                String[] lineParts = this.next().split("\s+");

                if (index % 5 == 0) {
                    writer.write(System.lineSeparator());
                    writer.write(this.formatString(1, String.format("%s, ", lineParts[0])));
                } else if (index % 5 == 4) {
                    writer.write(String.format("%s,", lineParts[0]));
                } else {
                    writer.write(String.format("%s, ", lineParts[0]));
                }

                index++;
            }
            writer.write(System.lineSeparator());
            writer.write(this.formatString(0, 1, "}"));
        }
    }

}
